//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeosIT.Exchange.GenericExchangeTransportAgent.Plugins.DkimSigningHandler.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeosIT.Exchange.GenericExchangeTransportAgent.Plugins.DkimSigningHandler.Properti" +
                            "es.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The encoded key is not in the proper DER format. ähnelt.
        /// </summary>
        internal static string CryptHelper_BadDerFormat {
            get {
                return ResourceManager.GetString("CryptHelper_BadDerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The encoded key is not in the proper PEM format. ähnelt.
        /// </summary>
        internal static string CryptHelper_BadPemFormat {
            get {
                return ResourceManager.GetString("CryptHelper_BadPemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MIME body could not be located, so DKIM signing was skipped. ähnelt.
        /// </summary>
        internal static string DkimSigningRoutingAgent_MimeBodyNotFound {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgent_MimeBodyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The PEM-encoded RSA Private Key is not specified, so DKIM signing was skipped. ähnelt.
        /// </summary>
        internal static string DkimSigningRoutingAgent_NoKey {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgent_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signing a mail item according to DKIM failed with an exception. Check the logged exception for details. ähnelt.
        /// </summary>
        internal static string DkimSigningRoutingAgent_SignFailed {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgent_SignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The algorithm specified in the configuration file could not be parsed. Check the value of the &apos;DefaultDkimSigner_Algorithm&apos; key under &lt;appSettings&gt;. Currently accepted values are &apos;RsaSha1&apos; (recommended) and &apos;RsaSha256&apos;. ähnelt.
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadAlgorithmConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadAlgorithmConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The domain was not found in the configuration file or is blank. Check the value of the &apos;DefaultDkimSigner_Domain&apos; key under the &lt;appSettings&gt; section. ähnelt.
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadDomainConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadDomainConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The PEM-encoded private RSA key was not found in the configuration file or is blank. Check the value of the &apos;DefaultDkimSigner_PrivateKey&apos; key in the &lt;appSettings&gt; section. ähnelt.
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadPrivateKeyConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadPrivateKeyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selector was not found in the configuration file or is blank. Check the value of the &apos;DefaultDkimSigner_Selector&apos; key under &lt;appSettings&gt;. ähnelt.
        /// </summary>
        internal static string DkimSigningRoutingAgentFactory_BadSelectorConfig {
            get {
                return ResourceManager.GetString("DkimSigningRoutingAgentFactory_BadSelectorConfig", resourceCulture);
            }
        }
    }
}
